services:
  redis:
    image: redis
  web:
    build:
      context: .
    environment:
      FLASK_APP: run
      FLASK_DEBUG: 1
      FLASK_DATABASE: ../instance/database.db
      CELERY_BROKER_URL: redis://redis
      CELERY_RESULT_BACKEND: redis://redis
    volumes:
      - .:/app
    command: uwsgi --http 0.0.0.0:5000 --master -p 4 -w run:app
    ports:
      - 5000:5000
  celery:
    build:
      context: .
    environment:
      FLASK_APP: run
    volumes:
      - .:/app
    command: celery -A run.celery worker --loglevel=info
    depends_on:
      - redis
